# Generated by Django 5.1.7 on 2025-03-23 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.FloatField(default=0, help_text='倉庫 X 軸座標')),
                ('location_y', models.FloatField(default=0, help_text='倉庫 Y 軸座標')),
                ('pending_cargo', models.IntegerField(default=0, help_text='待運送貨物數量')),
            ],
        ),
        migrations.AlterField(
            model_name='logisticsdata',
            name='dock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.dock'),
        ),
    ]
